name: Orchestrator
description: "GitHub Composite Action"

outputs:
  result_link:
    description: "Link from composite action"
    value: ${{ steps.myid.outputs.result_link }}

runs:
  using: 'composite'
  steps:

  - name: Setup Go
    uses: actions/setup-go@v5
    with:
      go-version: '1.23.4'

  - name:
    shell: bash
    run: |
      url=$(go run ${{ github.action_path }}/get-endpoint-url.go)
      echo $url
      
  
  - id: myid
    if: false
    shell: bash
    run: echo "result_link=$(echo "HOI")" >> $GITHUB_OUTPUT
    
