name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  first-job:
    permissions: write-all
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: echo "DATE=FOO" >> $GITHUB_ENV

      - name: Execute composite
        id: composite-run
        uses: TseJustin/gh-actions-sandbox@main

      - name: Capture output
        run: echo "${{ steps.composite-run.outputs.result_link }}"
