name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  first-job:
    permissions: write-all
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create repo variable
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/TseJustin/gh-actions/sandbox/actions/variables \
            -d '{"name":"USERNAME","value":"octo"}'
